version: '3.9'

services:
  blogsite:
    container_name: blogsite
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - REDIS_ADDRESS=redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_EXTENSIONS: "uuid-ossp"
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  pgdata: {}  